### ISSUE TITLE
Specify k8s version, check Deprecated API

### ISSUE THREAD

**Issue by wadason** [wadason/kubeval-kz-outputs-action#1]
## about
If you specify kubernetes-version, action detect the Deprecated api at that version.
I'm thinking about how to implement it.

If this feature is added, we must rethink the action name.

## details

```
- name: check manifest
  uses: wadason/kubeval-kz-outputs-action@v1
  with:
    pathList: k8s/apps, k8s/guestbook
    envList: staging, production
    kubernetes-version: 1.21 # ← new!
```

### output example
```
WARN: policy/v1beta1 〇〇 is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 〇〇 
```
